### A MNIST-like fashion product database

In this, we classify the images into respective classes given in the dataset. We use a Neural Net and a Deep Neural Net in Keras to solve this and check the accuracy scores.

### Load tensorflow

In [1]:
import tensorflow as tf
tf.set_random_seed(42)

In [2]:
tf.__version__

'1.13.1'

### Collect Data

In [3]:
import keras

Using TensorFlow backend.


In [4]:
(trainX, trainY), (testX, testY) = keras.datasets.fashion_mnist.load_data()

4423680/4422102 [==============================] - 2s 1us/step


In [7]:
trainY

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [5]:
print(testY[0:5])

[9 2 1 1 6]


### Convert both training and testing labels into one-hot vectors.

**Hint:** check **tf.keras.utils.to_categorical()**

In [8]:
trainY = tf.keras.utils.to_categorical(trainY, num_classes=10)
testY = tf.keras.utils.to_categorical(testY, num_classes=10)

In [9]:
print(trainY.shape)
print('First 5 examples now are: ', trainY[0:5])

(60000, 10)
First 5 examples now are:  [[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### Visualize the data

Plot first 10 images in the triaining set and their labels.

In [14]:
from PIL import Image
import numpy

In [18]:
print(trainX)
print(testX)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ...

### Build a neural Network with a cross entropy loss function and sgd optimizer in Keras. The output layer with 10 neurons as we have 10 classes.

In [19]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

#Reshape data from 2D to 1D -> 28x28 to 784
model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))

#Normalize the data
model.add(tf.keras.layers.BatchNormalization())

#Add Dense Layer which provides 10 Outputs after applying softmax
model.add(tf.keras.layers.Dense(10, activation='softmax'))

#Comile the model ((We will learn about optimizers it in the next residency))
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


### Execute the model using model.fit()

In [20]:
model.fit(trainX, trainY, 
          validation_data=(testX, testY), 
          epochs=50,
          batch_size=trainX.shape[0])

Train on 60000 samples, validate on 10000 samples
Instructions for updating:
Use tf.cast instead.
Epoch 1/50
60000/60000 [==============================] - 4s 60us/sample - loss: 3.0643 - acc: 0.0942 - val_loss: 12.7706 - val_acc: 0.1059
Epoch 2/50
60000/60000 [==============================] - 2s 39us/sample - loss: 2.7795 - acc: 0.1266 - val_loss: 11.3018 - val_acc: 0.1136
Epoch 3/50
60000/60000 [==============================] - 2s 38us/sample - loss: 2.5413 - acc: 0.1612 - val_loss: 9.9016 - val_acc: 0.1228
Epoch 4/50
60000/60000 [==============================] - 2s 37us/sample - loss: 2.3421 - acc: 0.1982 - val_loss: 8.5796 - val_acc: 0.1368
Epoch 5/50
60000/60000 [==============================] - 2s 37us/sample - loss: 2.1756 - acc: 0.2401 - val_loss: 7.3796 - val_acc: 0.1561
Epoch 6/50
60000/60000 [==============================] - 2s 38us/sample - loss: 2.0364 - acc: 0.2806 - val_loss: 6.3426 - val_acc: 0.1739
Epoch 7/50
60000/60000 [==============================] - 2s 39us/

### In the above Neural Network model add Batch Normalization layer after the input layer and repeat the steps.

In [0]:
#Already done above

### Execute the model

In [0]:
#See above

### Customize the learning rate to 0.001 in sgd optimizer and run the model

In [22]:
from keras import optimizers
learning_rate=0.001
sgd=optimizers.SGD(lr=learning_rate)

In [23]:
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

In [24]:
model.fit(trainX, trainY, 
          validation_data=(testX, testY), 
          epochs=50,
          batch_size=trainX.shape[0])

Train on 60000 samples, validate on 10000 samples
Epoch 1/50
60000/60000 [==============================] - 3s 49us/sample - loss: 0.9285 - acc: 0.6865 - val_loss: 1.1645 - val_acc: 0.6548
Epoch 2/50
60000/60000 [==============================] - 2s 37us/sample - loss: 0.9228 - acc: 0.6879 - val_loss: 1.1525 - val_acc: 0.6566
Epoch 3/50
60000/60000 [==============================] - 2s 37us/sample - loss: 0.9174 - acc: 0.6891 - val_loss: 1.1408 - val_acc: 0.6577
Epoch 4/50
60000/60000 [==============================] - 2s 36us/sample - loss: 0.9121 - acc: 0.6910 - val_loss: 1.1296 - val_acc: 0.6593
Epoch 5/50
60000/60000 [==============================] - 2s 36us/sample - loss: 0.9070 - acc: 0.6924 - val_loss: 1.1187 - val_acc: 0.6612
Epoch 6/50
60000/60000 [==============================] - 3s 45us/sample - loss: 0.9020 - acc: 0.6939 - val_loss: 1.1082 - val_acc: 0.6632
Epoch 7/50
60000/60000 [==============================] - 3s 47us/sample - loss: 0.8971 - acc: 0.6953 - val_loss: 1.

### Build the Neural Network model with 3 Dense layers with 100,100,10 neurons respectively in each layer. Use cross entropy loss function and singmoid as activation in the hidden layers and softmax as activation function in the output layer. Use sgd optimizer with learning rate 0.03.

In [32]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

#Reshape data from 2D to 1D -> 28x28 to 784
model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))

#Normalize the data
model.add(tf.keras.layers.BatchNormalization())

model.add(tf.keras.layers.Dense(100, activation='sigmoid'))
model.add(tf.keras.layers.Dense(100, activation='sigmoid'))


#Add Dense Layer which provides 10 Outputs after applying softmax
model.add(tf.keras.layers.Dense(10, activation='softmax'))



In [33]:
from keras import optimizers
learning_rate=0.03
sgd=optimizers.SGD(lr=learning_rate)

In [34]:
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

In [35]:
model.fit(trainX, trainY, 
          validation_data=(testX, testY), 
          epochs=50,
          batch_size=trainX.shape[0])

Train on 60000 samples, validate on 10000 samples
Epoch 1/50
60000/60000 [==============================] - 4s 60us/sample - loss: 2.9341 - acc: 0.1111 - val_loss: 2.8868 - val_acc: 0.1138
Epoch 2/50
60000/60000 [==============================] - 3s 46us/sample - loss: 2.8881 - acc: 0.1155 - val_loss: 2.8433 - val_acc: 0.1138
Epoch 3/50
60000/60000 [==============================] - 3s 46us/sample - loss: 2.8455 - acc: 0.1205 - val_loss: 2.8032 - val_acc: 0.1152
Epoch 4/50
60000/60000 [==============================] - 3s 45us/sample - loss: 2.8060 - acc: 0.1264 - val_loss: 2.7660 - val_acc: 0.1163
Epoch 5/50
60000/60000 [==============================] - 3s 45us/sample - loss: 2.7693 - acc: 0.1310 - val_loss: 2.7316 - val_acc: 0.1176
Epoch 6/50
60000/60000 [==============================] - 3s 44us/sample - loss: 2.7354 - acc: 0.1358 - val_loss: 2.6997 - val_acc: 0.1192
Epoch 7/50
60000/60000 [==============================] - 3s 44us/sample - loss: 2.7039 - acc: 0.1399 - val_loss: 2.

## Review model

### Run the model